#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

LRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'


run_linter () {
  echo -e "${PURPLE}Linting the src folder ==> ${NC}${CYAN}Ext: .js, .ts, .scss${NC}"
  pnpm exec lint-staged
  if [[ $? -ne 0 ]]
  then
    exit 1
  fi
}

check_branch () {
  if test "$(git branch --show-current)" == "master" || test "$(git branch --show-current)" == "main" || test "$(git branch --show-current)" == "development"
  then
    printf "You are on ${LRED}$(git branch --show-current)${NC}.\n"
    exit 1
  fi
}

no_console () {
  consoleRegexp='^[^-].*console.log'
  filenameRegexp='^[^-].*console.log(\|^+++'

  if test "$(git diff --cached | grep -c "$consoleRegexp")" != 0
  then
    git diff --cached | grep -ne "$filenameRegexp" | grep -B1 "$consoleRegexp"
    printf "\nSome files include ${LRED}console.log${NC}.\n"
    exit 1
  fi
}

### RUN THROUGH CHECKS AND STOP IF THERE IS A PROBLEM
run_linter
check_branch
no_console

printf "${GREEN}Proceeding with commit...${NC}\n"